### ISSUE TITLE
Smarthome node not working (could not find smarthome entity "undefined")

### ISSUE THREAD

**Issue by Dakyne** [586837r/node-red-contrib-alexa-remote2#35]
Hello,

Let's start with the _end_ : everything I tried works except the smarthome part of nodes. I'm using it like this :

![image](https://user-images.githubusercontent.com/23531224/62250479-46535c00-b3ed-11e9-9140-ce216190455f.png)

With the smarthome node I have this error : `"smarthome entity not found: """`
And with the routine smarthome : `"could not find smarthome entity: "undefined""`

In the config tab of smarthome node I have this : 

![image](https://user-images.githubusercontent.com/23531224/62250541-6daa2900-b3ed-11e9-9ea7-4c879b022e00.png)

Thanks for this addon !

**Comment by lukefairbank** [comment]
I get the same thing, burned heaps of time on it.

**Comment by 586837r** [comment]
What do you see in your browser's Developer Tools console when you open an *Alexa Smarthome* config?

**Comment by 586837r** [comment]
What browser is this? Does it behave the same way in Chrome/Firefox?

**Comment by Dakyne** [comment]
I'm not home, but I was using firefox on Linux, and nodered is runing as a homeassistant (hassos) addon in the provided VM by home assistant. I'll tell you what's in the console tonight ? (in 9 hours or something) ^^

**Comment by lukefairbank** [comment]
I have tried chrome, edge and Firefox. Not at home to check either though

Sent from Nine<http://www.9folders.com/>
________________________________

**Comment by Dakyne** [comment]
Okay I got this for an _Alexa Smarthome_ action : 
![image](https://user-images.githubusercontent.com/23531224/62391949-71ad8680-b566-11e9-8d91-b6459319c12f.png)

**Comment by 586837r** [comment]
Please make sure that XHR is enabled in the console filters. (response is interesting)
Do you get an error notification at the top of the page when you open the config?

**Comment by Dakyne** [comment]
Oh okay sorry. I get a 404 :
```
URL de la requête :http://192.168.1.150:8123/alexa-remote-smarthome.json?account=<account.id>
Méthode de la requête :GET
Adresse distante :ip:port
Code d’état : 404
Version : HTTP/1.1
```
Response header : 
```
HTTP/1.1 404 Not Found
Content-Type: text/plain; charset=utf-8
Content-Length: 14
Date: Fri, 02 Aug 2019 23:13:34 GMT
Server: Python/3.7 aiohttp/3.5.4
```

**Comment by 586837r** [comment]
Are you running 3.0.6? It has fixed a 404 error (#34)

**Comment by Dakyne** [comment]
Fixed … Since I installed a less than a week ago I didn't think there was already an update.

**Comment by mobamoba** [comment]
I'm still having this issue with the most recent version. When I click Get Entities, it lists all my Smarthome Devices in the message output. However, there's doesn't seem to be a way to apply an Action to an Entity as far as I can tell.

**Comment by 586837r** [comment]
@Dakyne Nice! No worries.
@mobamoba What exactly is wrong? Can you not select an entity in *Alexa Smarthome* node with the *Action* option? Is the "**Note:** Select an initialised account..." still showing?

**Comment by mobamoba** [comment]
My account is initialized and Routines, for example, work fine. I can't select an Entity in Alexa Smarthome. I get the same ??? options as in the screenshot in the initial post.

**Comment by 586837r** [comment]
If you don't see the "**Note:** Select an initialised account..." then either there is an Error while initialising the internal smarthome entities structure or you simply don't have any entity that supports at least 1 action.

Do you get a warning while the account is initialising? (You can trigger an initialisation with *Alexa Init*). 

You can look at the internal smarthome entities structure with a flow like this to see what entities have what actions:
  ```
[{"id":"e970fc13.85c32","type":"inject","z":"c0bfc064.e8d26","name":"","topic":"","payload":"","payloadType":"str","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":850,"y":200,"wires":[["fe8092e8.4f02f"]]},{"id":"912e5561.093b68","type":"debug","z":"c0bfc064.e8d26","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"payload","targetType":"msg","x":830,"y":320,"wires":[]},{"id":"e830f205.fc31f","type":"function","z":"c0bfc064.e8d26","name":"","func":"function map2obj(map) {\n    return Array.from(map.entries()).reduce((o,[k,v]) => (o[k] = v, o), {});\n}\n\nfunction isMap(o) {\n    return typeof o === 'object' && String(o) === '[object Map]';\n}\n\nif(isMap(msg.payload)) {\n    msg.payload = map2obj(msg.payload);\n}\n\nreturn msg;","outputs":1,"noerr":0,"x":850,"y":280,"wires":[["912e5561.093b68"]]}]
  ```

**Comment by mobamoba** [comment]
Sorry meant to say: I saw the select initialized account and selected the one I'd already initialized. I still got a bunch of ???. My result looks just like the screenshot in the first post, i.e. an initialized account selected the ??? in both lists. 

I get no warnings and account works perfectly fine. I'm using right now to trigger Alexa routines.

**Comment by 586837r** [comment]
The ??? is not an error in of itself. If you don't have any smarthome entity with at least 1 action then you will see ???. 
You can check the internal structure with the flow i posted before to check if you have an entity with an action.

**Comment by mobamoba** [comment]
I'm not sure what you mean by that. Perhaps I'm misunderstanding something: I have 3 Alexa smart plugs and want to be able to turn them on and off via Node Red. When I do a complete msg output from Get Entities, I can see my smart plugs listed there in various arrays. Where would they show up such that I could turn them on or off? Thanks.

**Comment by 586837r** [comment]
You should be able to select a smarthome device where you currently see "???". 
Just to debug it would be interesting what the smarthome "Simplified" structure looks like.

**Comment by mobamoba** [comment]
Sure - here's the output of Get Simplified:
```
msg : Object
object
payload: object
empty
_msgid: "2fb07cd0.5cdac4"
```

By contrast, here's what I see for Get Entities (I picked the first plug rather than cut/paste the whole thing):
```
msg : Object
object
payload: array[5]
0: object
id: "66003d9c-4b37-4891-b18f-7909a2d40616"
displayName: "Trunk Lamp"
description: "Amazon Smart Plug"
supportedProperties: array[2]
0: "turnOff"
1: "turnOn"
supportedTriggers: array[0]
supportedOperations: array[2]
0: "turnOff"
1: "turnOn"
availability: "AVAILABLE"
icon: object
value: "SMARTPLUG"
providerData: object
enabled: true
relationships: array[0]
categoryType: "APPLIANCE"
deviceType: "SMARTPLUG"
```

**Comment by 586837r** [comment]
Please get the simplified with this flow:
```
[{"id":"e970fc13.85c32","type":"inject","z":"c0bfc064.e8d26","name":"","topic":"","payload":"","payloadType":"str","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":850,"y":200,"wires":[["fe8092e8.4f02f"]]},{"id":"912e5561.093b68","type":"debug","z":"c0bfc064.e8d26","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"payload","targetType":"msg","x":830,"y":320,"wires":[]},{"id":"e830f205.fc31f","type":"function","z":"c0bfc064.e8d26","name":"","func":"function map2obj(map) {\n    return Array.from(map.entries()).reduce((o,[k,v]) => (o[k] = v, o), {});\n}\n\nfunction isMap(o) {\n    return typeof o === 'object' && String(o) === '[object Map]';\n}\n\nif(isMap(msg.payload)) {\n    msg.payload = map2obj(msg.payload);\n}\n\nreturn msg;","outputs":1,"noerr":0,"x":850,"y":280,"wires":[["912e5561.093b68"]]}]
```

And you can copy the output with this button: 
![Capture](https://user-images.githubusercontent.com/871782/62416484-f28a8200-b63b-11e9-8e72-1b75f1da8f54.PNG)

**Comment by mobamoba** [comment]
Imported your flow and inserted Smarthome Get Simplified with my account chosen between the Inject and the Function and go nothing:

![image](https://user-images.githubusercontent.com/11135869/62416890-010f7400-b611-11e9-88bc-0cca6a8e016d.png)

**Comment by lukefairbank** [comment]
I have the same issue on 3.0.6 and have run the flow you provided above. I also get the empty message as above. 
![image](https://user-images.githubusercontent.com/25714523/62417193-1c1fc980-b68d-11e9-9b45-a84366371212.png)

**Comment by 586837r** [comment]
Are you sure that you don't get a warning like 
![Capture](https://user-images.githubusercontent.com/871782/62417245-8b74c980-b64b-11e9-99db-1864be1ec395.PNG) 
in the console when initialising?

In any case you can send me the output json of Smarthome Get Devices and Smarthome Get Entities so i can see where it fails. You can send it directly to my email.

**Comment by mobamoba** [comment]
Is there private information in either of those? If not I'm fine posting here if that's easier.

**Comment by camphamp** [comment]
I received the same error message in the NR debug window: `"could not find smarthome entity: "undefined""`

It occurred immediately after a re-auth was performed (the nodes asked me to go to the proxy URL to grab a new cookie).

The re-auth reported success and cookie was saved, but then all applestrudel nodes failed to work and I saw the same empty entity list "???" reported above. I deleted the cookie and retried with same error result.

I have a second Amazon account (my wife's) that was assigned to 2 nodes and working, so I copied that cookie to the path for the non-working login and all the nodes resumed to function.

**Comment by mocallins** [comment]
I to am having this same issue.
Node-RED 4.0.9

I initially started with _node-red-contrib-alexa-remote2-v2_ ,
and have now tried _node-red-contrib-alexa-cakebaked_
I see the appelstrudel is the next fork, but don't really want to try another to run into the same issues.

And i will admit, i'm new to all the node-red community.

Still seeing same issue as, except the _everything I tried works except_  ;

> Hello,
> 
> Let's start with the _end_ : everything I tried works except the smarthome part of nodes. I'm using it like this for my tests :
> 
> ![image](https://user-images.githubusercontent.com/23531224/62250479-46535c00-b3ed-11e9-9140-ce216190455f.png)
> 
> With the smarthome node I have this error : `"smarthome entity not found: """` And with the routine smarthome : `"could not find smarthome entity: "undefined""`
> 
> In the config tab of smarthome node I have this :
> 
> ![image](https://user-images.githubusercontent.com/23531224/62250541-6daa2900-b3ed-11e9-9ea7-4c879b022e00.png)
> 
> Thanks for this addon !

**Comment by SpeedyBlade** [comment]
<img width="524" height="426" alt="Image" src="https://github.com/user-attachments/assets/7f1d1542-86c9-4082-b439-6fdabc09eb15" />

I have the same issue
Hub is connected. I can add additional devices but i can´t find any device in nodered. Same issue like my collegues before (???).
